name: hanhan
description: 涵涵的超级控制面板

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.5.1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_neumorphic: ^3.2.0
  shared_preferences: ^2.0.12
  cupertino_icons: ^1.0.2
  socket_io_client: ^2.0.0
  molten_navigationbar_flutter: ^1.0.0
  url_launcher: ^6.0.10
  introduction_screen: ^3.1.11
  provider: ^6.0.1
  win32: ^5.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
